import { headers } from 'next/headers'

/**
 * Reads the nonce generated by the proxy for the current request.
 *
 * Server Components and Pages should use this when rendering inline scripts
 * or passing a nonce down to <Script> components / client components that
 * inject third-party scripts. Because it reads request headers, any route
 * that calls it is opted into dynamic rendering — which nonce-based CSP
 * requires (Next.js can only apply nonces during SSR, not at build time).
 */
export async function getCspNonce(): Promise<string> {
  const headerStore = await headers()
  return headerStore.get('x-nonce') ?? ''
}