import type { BusinessSettings } from '@/lib/admin/business-settings'

export const FALLBACK_SETTINGS: BusinessSettings = {
  id: '',
  businessName: 'Flux3D',
  legalBusinessName: 'Flux3D Private Limited',
  brandName: 'Flux3D',
  tagline: 'Additive Innovation',
  businessDescription: 'Premium 3D printing services',
  gstNumber: '',
  panNumber: '',
  cinNumber: '',
  msmeNumber: '',
  businessType: '',
  primaryEmail: 'hello@flux3d.in',
  supportEmail: 'support@flux3d.com',
  salesEmail: 'sales@flux3d.in',
  billingEmail: 'billing@flux3d.in',
  primaryPhone: '+919623023480',
  whatsappNumber: '+919623023480',
  alternatePhone: '',
  tollFreeNumber: '',
  addressLine1: 'Mumbai, Maharashtra',
  addressLine2: '',
  landmark: '',
  city: 'Mumbai',
  state: 'Maharashtra',
  country: 'India',
  postalCode: '400053',
  billingSameAsOffice: true,
  billingAddressLine1: '',
  billingAddressLine2: '',
  billingCity: '',
  billingState: '',
  billingCountry: '',
  billingPostalCode: '',
  instagramUrl: 'https://instagram.com/flux3d',
  facebookUrl: '',
  linkedinUrl: 'https://linkedin.com/company/flux3d',
  twitterUrl: 'https://twitter.com/flux3d',
  youtubeUrl: 'https://youtube.com/@flux3d',
  threadsUrl: '',
  pinterestUrl: '',
  githubUrl: '',
  websiteUrl: '',
  logoUrl: '/logo.png',
  darkLogoUrl: '',
  faviconUrl: '/favicon.ico',
  invoiceLogoUrl: '',
  emailLogoUrl: '',
  primaryColor: '#7C5CFF',
  secondaryColor: '#A78BFA',
  invoicePrefix: 'INV-',
  quotationPrefix: 'QTN-',
  invoiceStartNumber: 1001,
  quotationStartNumber: 1001,
  currency: 'INR',
  currencySymbol: '₹',
  taxPercentage: 0,
  gstEnabled: false,
  cgstPercent: 0,
  sgstPercent: 0,
  sacHsnCode: '',
  paymentTerms: '',
  bankAccountName: '',
  bankName: '',
  accountNumber: '',
  ifscCode: '',
  upiId: '',
  upiQrCodeUrl: '',
  whatsappOrderNumber: '+919623023480',
  whatsappSupportNumber: '+919623023480',
  defaultWhatsappTemplate: '',
  autoReplyMessage: '',
  businessHours: 'Mon\u2014Sat: 9 AM \u2013 8 PM IST',
  supportAvailabilityMessage: '',
  metaTitle: 'Flux3D | Premium 3D Printing Services in India | \u20B999 Onwards',
  metaDescription: "India's most trusted 3D printing service in Mumbai. Industrial parts, architecture models, student projects & corporate gifts. Starting \u20B999. Pan-India delivery.",
  metaKeywords: '3D printing services India,3D printing Mumbai,rapid prototyping India,custom 3D printing,resin printing service,FDM printing service,3D modeling service,Bambu Lab 3D printing,industrial 3D printing,architecture models India,Flux3D',
  ogImageUrl: '/opengraph-image.png',
  twitterImageUrl: '',
  canonicalUrl: '',
  robotsIndex: true,
  smtpHost: '',
  smtpPort: 0,
  smtpUsername: '',
  smtpPassword: '',
  smtpSenderName: '',
  smtpSenderEmail: '',
  privacyPolicyUrl: '',
  termsUrl: '',
  refundPolicyUrl: '',
  shippingPolicyUrl: '',
  workingDays: 'Monday-Saturday',
  workingHours: '9 AM \u2013 8 PM',
  holidayMessage: '',
  emergencyContact: '',
  orderProcessingTime: '2-3 business days',
  deliveryChargeThreshold: 499,
  defaultDeliveryCharge: 50,
  overheadPercentage: 15,
  // Database migration 015/020 and pricing-waterfall.ts use this as the application fallback.
  marginPercentage: 30,
  materialMarkupPercent: 15,
  printSpeedGramsPerHour: 14.5,
  postProcessingMultipliers: {
    none: 0,
    sanded: 0.25,
    'sanded-painted': 0.6,
  },
  cartDiscountEnabled: true,
  cartDiscountTiers: [
    { minCartValue: 2000, discountPercent: 3 },
    { minCartValue: 5000, discountPercent: 5 },
    { minCartValue: 10000, discountPercent: 8 },
    { minCartValue: 20000, discountPercent: 12 },
  ],
  pickupAvailable: false,
  codAvailable: false,
  createdAt: '',
  updatedAt: '',
}

export function getFallbackSettings(): BusinessSettings {
  return FALLBACK_SETTINGS
}
