import type { BusinessSettings } from '@/lib/admin/business-settings'

export const FALLBACK_SETTINGS: BusinessSettings = {
  id: '',
  businessName: 'Flux3D',
  legalBusinessName: 'Flux3D',
  brandName: 'Flux3D',
  tagline: 'Custom 3D Printing and Manufacturing Services',
  businessDescription: 'Custom 3D printing and custom manufacturing services',
  gstNumber: '',
  panNumber: '',
  cinNumber: '',
  msmeNumber: '',
  businessType: '',
  primaryEmail: 'flux3d.in@gmail.com',
  supportEmail: 'flux3d.in@gmail.com',
  salesEmail: 'flux3d.in@gmail.com',
  billingEmail: 'flux3d.in@gmail.com',
  primaryPhone: '+919623023480',
  whatsappNumber: '+919623023480',
  alternatePhone: '',
  tollFreeNumber: '',
  addressLine1: 'Sawargaon Tal, Sangamner',
  addressLine2: '',
  landmark: '',
  city: 'Ahmednagar',
  state: 'Maharashtra',
  country: 'India',
  postalCode: '422605',
  billingSameAsOffice: true,
  billingAddressLine1: '',
  billingAddressLine2: '',
  billingCity: '',
  billingState: '',
  billingCountry: '',
  billingPostalCode: '',
  instagramUrl: 'https://instagram.com/flux3d',
  facebookUrl: '',
  linkedinUrl: 'https://linkedin.com/company/flux3d',
  twitterUrl: 'https://twitter.com/flux3d',
  youtubeUrl: 'https://youtube.com/@flux3d',
  threadsUrl: '',
  pinterestUrl: '',
  githubUrl: '',
  websiteUrl: '',
  logoUrl: '/logo.webp',
  darkLogoUrl: '',
  faviconUrl: '/favicon.ico',
  invoiceLogoUrl: '',
  emailLogoUrl: '',
  primaryColor: '#6d28d9',
  secondaryColor: '#a855f7',
  invoicePrefix: 'INV-',
  quotationPrefix: 'QTN-',
  invoiceStartNumber: 1001,
  quotationStartNumber: 1001,
  currency: 'INR',
  currencySymbol: '₹',
  taxPercentage: 0,
  gstEnabled: false,
  cgstPercent: 0,
  sgstPercent: 0,
  sacHsnCode: '',
  paymentTerms: '',
  bankAccountName: '',
  bankName: '',
  accountNumber: '',
  ifscCode: '',
  upiId: '',
  upiQrCodeUrl: '',
  whatsappOrderNumber: '+919623023480',
  whatsappSupportNumber: '+919623023480',
  defaultWhatsappTemplate: '',
  autoReplyMessage: '',
  businessHours: '',
  supportAvailabilityMessage: '',
  metaTitle: 'Flux3D | Custom 3D Printing and Manufacturing Services in India',
  metaDescription: 'Flux3D provides custom 3D printing, prototyping, model printing and related manufacturing services across India.',
  metaKeywords: 'custom 3D printing India,3D printing service India,rapid prototyping India,custom manufacturing,ready-made 3D products,Flux3D',
  ogImageUrl: '/opengraph-image.png',
  twitterImageUrl: '',
  canonicalUrl: '',
  robotsIndex: true,
  smtpHost: '',
  smtpPort: 0,
  smtpUsername: '',
  smtpPassword: '',
  smtpSenderName: '',
  smtpSenderEmail: '',
  resendApiKey: '',
  resendSenderDomain: 'updates.flux3d.in',
  resendSenderName: 'Flux3D',
  resendSenderEmail: 'noreply@updates.flux3d.in',
  resendWebhookSecret: '',
  privacyPolicyUrl: '',
  termsUrl: '',
  refundPolicyUrl: '',
  shippingPolicyUrl: '',
  workingDays: 'Monday-Saturday',
  workingHours: '9 AM \u2013 8 PM',
  holidayMessage: '',
  emergencyContact: '',
  orderProcessingTime: '2-3 business days',
  deliveryChargeThreshold: 499,
  defaultDeliveryCharge: 50,
  overheadPercentage: 15,
  // Database migration 015/020 and pricing-waterfall.ts use this as the application fallback.
  marginPercentage: 30,
  materialMarkupPercent: 15,
  printSpeedGramsPerHour: 14.5,
  postProcessingMultipliers: {
    none: 0,
    sanded: 0.25,
    'sanded-painted': 0.6,
  },
  cartDiscountEnabled: true,
  cartDiscountTiers: [
    { minCartValue: 2000, discountPercent: 3 },
    { minCartValue: 5000, discountPercent: 5 },
    { minCartValue: 10000, discountPercent: 8 },
    { minCartValue: 20000, discountPercent: 12 },
  ],
  pickupAvailable: false,
  codAvailable: false,
  paymentsEnabled: true,
  razorpayEnabled: true,
  razorpayKeyId: '',
  razorpayEnvironment: 'test',
  razorpayCheckoutName: 'Flux3D',
  razorpayCheckoutDescription: 'Secure payment for Flux3D orders',
  razorpayBrandColor: '#0f172a',
  razorpayPaymentMethods: '',
  razorpayTimeoutMinutes: 10,
  razorpayOrderBufferMinutes: 15,
  razorpayWebhookHealthy: false,
  razorpayLastConnectionCheckAt: '',
  razorpayLastConnectionStatus: '',
  razorpayLastConnectionMessage: '',
  razorpayRefundPermissionMode: 'admin',
  createdAt: '',
  updatedAt: '',
}

export function getFallbackSettings(): BusinessSettings {
  return FALLBACK_SETTINGS
}
