-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create storage.foldername() function (fixes 42704 error)
CREATE OR REPLACE FUNCTION storage.foldername(name text)
RETURNS text[]
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  RETURN string_to_array(name, '/');
END;
$$;

-- 1. Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  name text,
  email text NOT NULL,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. Orders table (created BEFORE quotes due to FK)
CREATE TABLE IF NOT EXISTS public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  serial_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  order_number text UNIQUE,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  group_id uuid,
  file_url text NOT NULL,
  material text NOT NULL,
  color text NOT NULL,
  infill integer NOT NULL,
  layer_height numeric NOT NULL,
  supports boolean NOT NULL DEFAULT false,
  full_name text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  address_line1 text NOT NULL DEFAULT '',
  address_line2 text,
  city text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT '',
  pincode text NOT NULL DEFAULT '',
  landmark text,
  delivery_charge numeric(10,2) NOT NULL DEFAULT 0,
  total_price numeric(10,2) NOT NULL DEFAULT 0,
  price numeric(10,2) NOT NULL,
  estimated_time numeric(10,2) NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT orders_status_check CHECK (
    status IN ('pending', 'reviewed', 'approved', 'queued', 'on-hold', 'printing', 'shipped', 'completed', 'rejected', 'cancelled')
  )
);

-- 3. Quotes table (references orders via converted_to_order_id)
CREATE TABLE IF NOT EXISTS public.quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid REFERENCES auth.users (id) ON DELETE CASCADE,
  quote_id text,
  file_path text,
  config jsonb,
  estimate jsonb,
  notes text,
  time_spent_seconds integer,
  reached_payment boolean DEFAULT false,
  abandoned_at timestamptz,
  abandoned_reason text,
  converted_to_order_id uuid REFERENCES public.orders (id) ON DELETE SET NULL,
  layer_height numeric(4,2)
);

-- 4. Delivery addresses table
CREATE TABLE IF NOT EXISTS public.delivery_addresses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  full_name text NOT NULL,
  phone text NOT NULL,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state text NOT NULL,
  pincode text NOT NULL,
  landmark text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 5. Materials table
CREATE TABLE IF NOT EXISTS public.materials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  price_per_gram numeric(10,2) NOT NULL DEFAULT 0,
  density numeric(10,2) NOT NULL DEFAULT 0,
  colors jsonb NOT NULL DEFAULT '[]'::jsonb,
  stock text NOT NULL DEFAULT 'Healthy',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT materials_stock_check CHECK (stock IN ('Healthy', 'Low', 'Paused'))
);

-- Insert default materials
INSERT INTO public.materials (name, price_per_gram, density, colors, stock)
VALUES 
  ('pla-plus', 2.80, 1.24, '[{"name": "Arctic White", "hex": "#f3f4f6"}, {"name": "Graphite", "hex": "#1f2937"}, {"name": "Signal Orange", "hex": "#ff5c1a"}]', 'Healthy'),
  ('abs', 4.10, 1.04, '[{"name": "Industrial Black", "hex": "#111827"}, {"name": "Slate Gray", "hex": "#4b5563"}, {"name": "Safety Yellow", "hex": "#facc15"}]', 'Healthy')
ON CONFLICT (name) DO NOTHING;

-- 6. Create storage bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('quote-models', 'quote-models', false, 104857600)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

-- Profiles policies
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT TO authenticated
USING (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_upsert_own" ON public.profiles;
CREATE POLICY "profiles_upsert_own" ON public.profiles FOR INSERT TO authenticated
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated
USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Quotes policies
DROP POLICY IF EXISTS "quotes_select_own" ON public.quotes;
CREATE POLICY "quotes_select_own" ON public.quotes FOR SELECT TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "quotes_insert_own" ON public.quotes;
CREATE POLICY "quotes_insert_own" ON public.quotes FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "quotes_update_own" ON public.quotes;
CREATE POLICY "quotes_update_own" ON public.quotes FOR UPDATE TO authenticated
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "quotes_delete_own" ON public.quotes;
CREATE POLICY "quotes_delete_own" ON public.quotes FOR DELETE TO authenticated
USING (auth.uid() = user_id);

-- Orders policies
DROP POLICY IF EXISTS "orders_select_own" ON public.orders;
CREATE POLICY "orders_select_own" ON public.orders FOR SELECT TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "orders_insert_own" ON public.orders;
CREATE POLICY "orders_insert_own" ON public.orders FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "orders_update_own" ON public.orders;
CREATE POLICY "orders_update_own" ON public.orders FOR UPDATE TO authenticated
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Delivery addresses policies
DROP POLICY IF EXISTS "delivery_addresses_select_own" ON public.delivery_addresses;
CREATE POLICY "delivery_addresses_select_own" ON public.delivery_addresses FOR SELECT TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "delivery_addresses_insert_own" ON public.delivery_addresses;
CREATE POLICY "delivery_addresses_insert_own" ON public.delivery_addresses FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delivery_addresses_update_own" ON public.delivery_addresses;
CREATE POLICY "delivery_addresses_update_own" ON public.delivery_addresses FOR UPDATE TO authenticated
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delivery_addresses_delete_own" ON public.delivery_addresses;
CREATE POLICY "delivery_addresses_delete_own" ON public.delivery_addresses FOR DELETE TO authenticated
USING (auth.uid() = user_id);

-- Materials policies (allow all authenticated users to read, admin to manage)
DROP POLICY IF EXISTS "materials_select_all" ON public.materials;
CREATE POLICY "materials_select_all" ON public.materials FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "materials_insert_admin" ON public.materials;
CREATE POLICY "materials_insert_admin" ON public.materials FOR INSERT TO authenticated
WITH CHECK (auth.jwt() ->> 'role' = 'admin' OR auth.jwt() -> 'email' = 'admin@flux3d.com');

DROP POLICY IF EXISTS "materials_update_admin" ON public.materials;
CREATE POLICY "materials_update_admin" ON public.materials FOR UPDATE TO authenticated
USING (auth.jwt() ->> 'role' = 'admin' OR auth.jwt() -> 'email' = 'admin@flux3d.com')
WITH CHECK (auth.jwt() ->> 'role' = 'admin' OR auth.jwt() -> 'email' = 'admin@flux3d.com');

DROP POLICY IF EXISTS "materials_delete_admin" ON public.materials;
CREATE POLICY "materials_delete_admin" ON public.materials FOR DELETE TO authenticated
USING (auth.jwt() ->> 'role' = 'admin' OR auth.jwt() -> 'email' = 'admin@flux3d.com');

-- Storage policies (fixes 42704 error - storage.foldername() now exists)
DROP POLICY IF EXISTS "quote_models_select_own" ON storage.objects;
CREATE POLICY "quote_models_select_own" ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "quote_models_insert_own" ON storage.objects;
CREATE POLICY "quote_models_insert_own" ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "quote_models_update_own" ON storage.objects;
CREATE POLICY "quote_models_update_own" ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "quote_models_delete_own" ON storage.objects;
CREATE POLICY "quote_models_delete_own" ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
);
