-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create storage.foldername() function (fixes 42704 error)
CREATE OR REPLACE FUNCTION storage.foldername(name text)
RETURNS text[]
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  RETURN string_to_array(name, '/');
END;
$$;

-- 1. Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  name text,
  email text NOT NULL,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. Orders table (created BEFORE quotes due to FK)
CREATE TABLE IF NOT EXISTS public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  serial_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  order_number text UNIQUE,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  group_id uuid,
  file_url text NOT NULL,
  material text NOT NULL,
  color text NOT NULL,
  infill integer NOT NULL,
  layer_height numeric NOT NULL,
  supports boolean NOT NULL DEFAULT false,
  full_name text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  address_line1 text NOT NULL DEFAULT '',
  address_line2 text,
  city text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT '',
  pincode text NOT NULL DEFAULT '',
  landmark text,
  delivery_charge numeric(10,2) NOT NULL DEFAULT 0,
  material_cost numeric(10,2) NOT NULL DEFAULT 0,
  machine_cost numeric(10,2) NOT NULL DEFAULT 0,
  post_processing_level text NOT NULL DEFAULT 'none',
  post_processing_charges numeric(10,2) NOT NULL DEFAULT 0,
  subtotal numeric(10,2) NOT NULL DEFAULT 0,
  overhead_percent numeric(5,2) NOT NULL DEFAULT 0,
  overhead_amount numeric(10,2) NOT NULL DEFAULT 0,
  margin_percent numeric(5,2) NOT NULL DEFAULT 0,
  margin_amount numeric(10,2) NOT NULL DEFAULT 0,
  total_price numeric(10,2) NOT NULL DEFAULT 0,
  final_price numeric(10,2) NOT NULL DEFAULT 0,
  grand_total numeric(10,2) NOT NULL DEFAULT 0,
  price numeric(10,2) NOT NULL,
  price_per_unit numeric(10,2) NOT NULL DEFAULT 0,
  estimated_time numeric(10,2) NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  weight numeric(10,2) NOT NULL DEFAULT 0,
  difficulty_factor numeric(10,2) NOT NULL DEFAULT 1,
  discount numeric(10,2) NOT NULL DEFAULT 0,
  cart_discount numeric(10,2) NOT NULL DEFAULT 0,
  cart_discount_percent numeric(5,2) NOT NULL DEFAULT 0,
  coupon_discount numeric(10,2) NOT NULL DEFAULT 0,
  coupon_code text,
  coupon_id uuid,
  discount_type text,
  offer_id uuid,
  offer_discount numeric(10,2) NOT NULL DEFAULT 0,
  offer_name text,
  cancel_requested boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'pending',
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT orders_status_check CHECK (
    status IN ('pending', 'confirmed', 'printing', 'shipped', 'delivered', 'completed', 'cancelled')
  )
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at_desc ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_group_id ON public.orders(group_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON public.orders(order_number);

-- 3. Quotes table (references orders via converted_to_order_id)
CREATE TABLE IF NOT EXISTS public.quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid REFERENCES auth.users (id) ON DELETE CASCADE,
  quote_id text,
  file_path text,
  config jsonb,
  estimate jsonb,
  notes text,
  time_spent_seconds integer,
  reached_payment boolean DEFAULT false,
  abandoned_at timestamptz,
  abandoned_reason text,
  converted_to_order_id uuid REFERENCES public.orders (id) ON DELETE SET NULL,
  layer_height numeric(4,2)
);

-- 4. Delivery addresses table
CREATE TABLE IF NOT EXISTS public.delivery_addresses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  full_name text NOT NULL,
  phone text NOT NULL,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state text NOT NULL,
  pincode text NOT NULL,
  landmark text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 5. Materials table
CREATE TABLE IF NOT EXISTS public.materials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  price_per_gram numeric(10,2) NOT NULL DEFAULT 0,
  density numeric(10,2) NOT NULL DEFAULT 0,
  colors jsonb NOT NULL DEFAULT '[]'::jsonb,
  stock text NOT NULL DEFAULT 'Healthy',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT materials_stock_check CHECK (stock IN ('Healthy', 'Low', 'Paused'))
);

-- 6. Business settings table
CREATE TABLE IF NOT EXISTS public.business_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_name text,
  legal_business_name text,
  brand_name text,
  tagline text,
  business_description text,
  gst_number text,
  pan_number text,
  cin_number text,
  msme_number text,
  business_type text DEFAULT 'Individual',
  primary_email text,
  support_email text,
  sales_email text,
  billing_email text,
  primary_phone text,
  whatsapp_number text,
  alternate_phone text,
  toll_free_number text,
  address_line_1 text,
  address_line_2 text,
  landmark text,
  city text,
  state text,
  country text DEFAULT 'India',
  postal_code text,
  billing_same_as_office boolean DEFAULT true,
  billing_address_line_1 text,
  billing_address_line_2 text,
  billing_city text,
  billing_state text,
  billing_country text,
  billing_postal_code text,
  instagram_url text,
  facebook_url text,
  linkedin_url text,
  twitter_url text,
  youtube_url text,
  threads_url text,
  pinterest_url text,
  github_url text,
  website_url text,
  logo_url text,
  dark_logo_url text,
  favicon_url text,
  invoice_logo_url text,
  email_logo_url text,
  primary_color text DEFAULT '#FF5C1A',
  secondary_color text DEFAULT '#39BDF8',
  invoice_prefix text DEFAULT 'INV-',
  quotation_prefix text DEFAULT 'QTN-',
  invoice_start_number integer DEFAULT 1001,
  quotation_start_number integer DEFAULT 1001,
  currency text DEFAULT 'INR',
  currency_symbol text DEFAULT '₹',
  tax_percentage numeric(5,2) DEFAULT 0,
  gst_enabled boolean NOT NULL DEFAULT false,
  cgst_percent numeric(5,2) NOT NULL DEFAULT 0,
  sgst_percent numeric(5,2) NOT NULL DEFAULT 0,
  sac_hsn_code text,
  payment_terms text,
  bank_account_name text,
  bank_name text,
  account_number text,
  ifsc_code text,
  upi_id text,
  upi_qr_code_url text,
  whatsapp_order_number text,
  whatsapp_support_number text,
  default_whatsapp_template text,
  auto_reply_message text,
  business_hours text,
  support_availability_message text,
  meta_title text,
  meta_description text,
  meta_keywords text,
  og_image_url text,
  twitter_image_url text,
  canonical_url text,
  robots_index boolean DEFAULT true,
  smtp_host text,
  smtp_port integer,
  smtp_username text,
  smtp_password text,
  smtp_sender_name text,
  smtp_sender_email text,
  privacy_policy_url text,
  terms_url text,
  refund_policy_url text,
  shipping_policy_url text,
  working_days text,
  working_hours text,
  holiday_message text,
  emergency_contact text,
  order_processing_time text,
  delivery_charge_threshold numeric(10,2) DEFAULT 499,
  default_delivery_charge numeric(10,2) DEFAULT 50,
  overhead_percent numeric(5,2) NOT NULL DEFAULT 15,
  margin_percentage numeric(5,2) NOT NULL DEFAULT 30,
  material_markup_percent numeric(5,2) NOT NULL DEFAULT 15,
  print_speed_grams_per_hour numeric(10,2) NOT NULL DEFAULT 14.5,
  post_processing_multipliers jsonb NOT NULL DEFAULT '{"none":0,"sanded":0.25,"sanded-painted":0.6}'::jsonb,
  cart_discount_enabled boolean NOT NULL DEFAULT true,
  cart_discount_tiers jsonb NOT NULL DEFAULT '[]'::jsonb,
  pickup_available boolean DEFAULT false,
  cod_available boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_business_settings_single_row
ON public.business_settings ((deleted_at IS NULL))
WHERE deleted_at IS NULL;

-- Insert default materials
INSERT INTO public.materials (name, price_per_gram, density, colors, stock)
VALUES 
  ('pla-plus', 2.80, 1.24, '[{"name": "Arctic White", "hex": "#f3f4f6"}, {"name": "Graphite", "hex": "#1f2937"}, {"name": "Signal Orange", "hex": "#ff5c1a"}]', 'Healthy'),
  ('abs', 4.10, 1.04, '[{"name": "Industrial Black", "hex": "#111827"}, {"name": "Slate Gray", "hex": "#4b5563"}, {"name": "Safety Yellow", "hex": "#facc15"}]', 'Healthy')
ON CONFLICT (name) DO NOTHING;

-- 7. Create storage bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('quote-models', 'quote-models', false, 104857600)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_settings ENABLE ROW LEVEL SECURITY;

-- Profiles policies
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT TO authenticated
USING (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_upsert_own" ON public.profiles;
CREATE POLICY "profiles_upsert_own" ON public.profiles FOR INSERT TO authenticated
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated
USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Auto-create a profile whenever a new auth user is created
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, created_at)
  VALUES (NEW.id, COALESCE(NEW.email, ''), now())
  ON CONFLICT (id) DO UPDATE
    SET email = EXCLUDED.email;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- Quotes policies
DROP POLICY IF EXISTS "quotes_select_own" ON public.quotes;
CREATE POLICY "quotes_select_own" ON public.quotes FOR SELECT TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "quotes_insert_own" ON public.quotes;
CREATE POLICY "quotes_insert_own" ON public.quotes FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "quotes_update_own" ON public.quotes;
CREATE POLICY "quotes_update_own" ON public.quotes FOR UPDATE TO authenticated
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "quotes_delete_own" ON public.quotes;
CREATE POLICY "quotes_delete_own" ON public.quotes FOR DELETE TO authenticated
USING (auth.uid() = user_id);

-- Orders policies
DROP POLICY IF EXISTS "orders_select_own" ON public.orders;
CREATE POLICY "orders_select_own" ON public.orders FOR SELECT TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "orders_insert_own" ON public.orders;
CREATE POLICY "orders_insert_own" ON public.orders FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "orders_update_own" ON public.orders;
CREATE POLICY "orders_update_own" ON public.orders FOR UPDATE TO authenticated
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

REVOKE UPDATE ON public.orders FROM authenticated;
GRANT UPDATE (
  full_name,
  phone,
  address_line1,
  address_line2,
  city,
  state,
  pincode,
  landmark,
  notes,
  cancel_requested,
  updated_at
) ON public.orders TO authenticated;

-- Delivery addresses policies
DROP POLICY IF EXISTS "delivery_addresses_select_own" ON public.delivery_addresses;
CREATE POLICY "delivery_addresses_select_own" ON public.delivery_addresses FOR SELECT TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "delivery_addresses_insert_own" ON public.delivery_addresses;
CREATE POLICY "delivery_addresses_insert_own" ON public.delivery_addresses FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delivery_addresses_update_own" ON public.delivery_addresses;
CREATE POLICY "delivery_addresses_update_own" ON public.delivery_addresses FOR UPDATE TO authenticated
USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delivery_addresses_delete_own" ON public.delivery_addresses;
CREATE POLICY "delivery_addresses_delete_own" ON public.delivery_addresses FOR DELETE TO authenticated
USING (auth.uid() = user_id);

-- Materials policies (allow all authenticated users to read, admin to manage)
DROP POLICY IF EXISTS "materials_select_all" ON public.materials;
CREATE POLICY "materials_select_all" ON public.materials FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "materials_insert_admin" ON public.materials;
CREATE POLICY "materials_insert_admin" ON public.materials FOR INSERT TO authenticated
WITH CHECK (auth.jwt() ->> 'role' = 'admin' OR auth.jwt() -> 'email' = 'admin@flux3d.com');

DROP POLICY IF EXISTS "materials_update_admin" ON public.materials;
CREATE POLICY "materials_update_admin" ON public.materials FOR UPDATE TO authenticated
USING (auth.jwt() ->> 'role' = 'admin' OR auth.jwt() -> 'email' = 'admin@flux3d.com')
WITH CHECK (auth.jwt() ->> 'role' = 'admin' OR auth.jwt() -> 'email' = 'admin@flux3d.com');

DROP POLICY IF EXISTS "materials_delete_admin" ON public.materials;
CREATE POLICY "materials_delete_admin" ON public.materials FOR DELETE TO authenticated
USING (auth.jwt() ->> 'role' = 'admin' OR auth.jwt() -> 'email' = 'admin@flux3d.com');

DROP POLICY IF EXISTS "business_settings_public_read" ON public.business_settings;
CREATE POLICY "business_settings_public_read" ON public.business_settings FOR SELECT
USING (deleted_at IS NULL);

-- Storage policies (fixes 42704 error - storage.foldername() now exists)
DROP POLICY IF EXISTS "quote_models_select_own" ON storage.objects;
CREATE POLICY "quote_models_select_own" ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "quote_models_insert_own" ON storage.objects;
CREATE POLICY "quote_models_insert_own" ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "quote_models_update_own" ON storage.objects;
CREATE POLICY "quote_models_update_own" ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "quote_models_delete_own" ON storage.objects;
CREATE POLICY "quote_models_delete_own" ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id = 'quote-models'
  AND (storage.foldername(name))[1] = auth.uid()::text
);
