create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text,
  email text not null,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  message text,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public, file_size_limit)
values ('quote-models', 'quote-models', false, 104857600)
on conflict (id) do nothing;

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_upsert_own" on public.profiles;
create policy "profiles_upsert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

alter table public.quotes
  add column if not exists user_id uuid references auth.users (id) on delete cascade,
  add column if not exists quote_id text,
  add column if not exists file_path text,
  add column if not exists config jsonb,
  add column if not exists estimate jsonb,
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default now();

alter table public.quotes enable row level security;

drop policy if exists "quotes_select_own" on public.quotes;
create policy "quotes_select_own"
on public.quotes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "quotes_insert_own" on public.quotes;
create policy "quotes_insert_own"
on public.quotes
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "quotes_update_own" on public.quotes;
create policy "quotes_update_own"
on public.quotes
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "quotes_delete_own" on public.quotes;
create policy "quotes_delete_own"
on public.quotes
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "quote_models_select_own" on storage.objects;
create policy "quote_models_select_own"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'quote-models'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "quote_models_insert_own" on storage.objects;
create policy "quote_models_insert_own"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'quote-models'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "quote_models_update_own" on storage.objects;
create policy "quote_models_update_own"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'quote-models'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'quote-models'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "quote_models_delete_own" on storage.objects;
create policy "quote_models_delete_own"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'quote-models'
  and (storage.foldername(name))[1] = auth.uid()::text
);
