-- Bootstrap tables needed by early numeric migrations.
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT, email TEXT NOT NULL DEFAULT '', full_name TEXT,
  avatar_url TEXT, phone_number TEXT,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  is_finance BOOLEAN NOT NULL DEFAULT false,
  is_order_manager BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  serial_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  order_number TEXT UNIQUE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  group_id UUID,
  file_url TEXT NOT NULL DEFAULT '',
  material TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '',
  infill INTEGER NOT NULL DEFAULT 50,
  layer_height NUMERIC NOT NULL DEFAULT 0.2,
  supports BOOLEAN NOT NULL DEFAULT false,
  quantity INTEGER NOT NULL DEFAULT 1,
  weight NUMERIC(10,2) NOT NULL DEFAULT 0,
  difficulty_factor NUMERIC(10,2) NOT NULL DEFAULT 1,
  full_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  address_line1 TEXT NOT NULL DEFAULT '',
  address_line2 TEXT,
  city TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT '',
  pincode TEXT NOT NULL DEFAULT '',
  landmark TEXT,
  delivery_charge NUMERIC(10,2) NOT NULL DEFAULT 0,
  material_cost NUMERIC(10,2) NOT NULL DEFAULT 0,
  machine_cost NUMERIC(10,2) NOT NULL DEFAULT 0,
  post_processing_level TEXT NOT NULL DEFAULT 'none',
  post_processing_charges NUMERIC(10,2) NOT NULL DEFAULT 0,
  subtotal NUMERIC(10,2) NOT NULL DEFAULT 0,
  overhead_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  overhead_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  margin_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  margin_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  total_price NUMERIC(10,2) NOT NULL DEFAULT 0,
  final_price NUMERIC(10,2) NOT NULL DEFAULT 0,
  grand_total NUMERIC(10,2) NOT NULL DEFAULT 0,
  price NUMERIC(10,2) NOT NULL DEFAULT 0,
  price_per_unit NUMERIC(10,2) NOT NULL DEFAULT 0,
  estimated_time NUMERIC(10,2) NOT NULL DEFAULT 0,
  discount NUMERIC(10,2) NOT NULL DEFAULT 0,
  coupon_code TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.profiles (id, email, full_name)
SELECT id, email, 'Test User' FROM auth.users
WHERE email = 'test@example.com'
  AND NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.users.id)
ON CONFLICT (id) DO NOTHING;
