-- ============================================================================
-- Migration: Magic-link login email (guest account claiming)
-- Date: 2026-08-23
-- Purpose:
--   * email_logs.email_type: add 'magic_link_login'
--   * Seed the system email_templates row.
-- The link itself is generated by supabase.auth.admin.generateLink() and
-- delivered through the Resend pipeline (src/app/api/account/send-magic-link).
-- ============================================================================

DO $$
DECLARE
  cname text;
BEGIN
  SELECT conname INTO cname
  FROM pg_constraint
  WHERE conrelid = 'public.email_logs'::regclass
    AND contype = 'c'
    AND conname LIKE 'email_logs_email_type%';

  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.email_logs DROP CONSTRAINT IF EXISTS %I', cname);
  END IF;

  ALTER TABLE public.email_logs ADD CONSTRAINT email_logs_email_type_check
    CHECK (email_type IN ('welcome','email_verification','password_reset','password_changed',
      'order_placed_customer','order_placed_admin','model_validation_pass','model_validation_fail',
      'production_started','order_shipped','delivery_confirmation','review_reminder',
      'payment_receipt','payment_failed','refund_issued','contact_notification',
      'account_link_confirmation','stock_alert','back_in_stock','ticket_acknowledgment',
      'out_for_delivery','magic_link_login'));
END $$;

INSERT INTO public.email_templates (
  name, email_type, category, subject, html_body, plain_text, variables,
  is_enabled, is_system, description
)
SELECT
  'Magic link login',
  'magic_link_login',
  'transactional',
  'Your Flux3D login link',
  '<p style="font-size:22px;font-weight:700;color:#1a1a1a;margin:0 0 12px;" class="email-text">Hello,</p>
<p style="font-size:15px;line-height:1.6;color:#6b7280;margin:0 0 12px;" class="email-muted">
  Click the button below to securely access your Flux3D account and save your guest order(s) to it.
</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center" style="padding:8px 0 24px;">
  <a href="{{login_url}}" style="background-color:#FF5C1A;color:#fff;padding:14px 24px;border-radius:8px;font-size:15px;font-weight:600;text-decoration:none;display:inline-block;">Log in to Flux3D</a>
</td></tr></table>
<p style="font-size:13px;color:#6b7280;text-align:center;margin:0 0 8px;" class="email-muted">
  This link works once and expires in {{expires_in_minutes}} minutes.
</p>
<p style="font-size:13px;color:#6b7280;text-align:center;margin:0;" class="email-muted">
  Didn''t request this? You can safely ignore this email — no account changes will be made. Questions? <a href="mailto:{{support_email}}" style="color:#39BDF8;">{{support_email}}</a>
</p>',
  'Click the link to securely log in to Flux3D and save your guest orders to your account. Works once, expires in {{expires_in_minutes}} minutes.',
  '["login_url","expires_in_minutes"]'::jsonb,
  TRUE, TRUE,
  'One-time login link for guest checkout claiming. Sent via /api/account/send-magic-link.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.email_templates WHERE email_type = 'magic_link_login' AND is_system = TRUE
);
