-- RPC to find and clean up orphaned model files in the quote-models bucket.
-- Orphaned = files not referenced by any orders, quotes, or model_files row,
-- and older than the specified grace period (24 hours by default).
--
-- Usage: SELECT * FROM public.cleanup_orphan_models(24); -- 24 hours grace period

CREATE OR REPLACE FUNCTION public.cleanup_orphan_models(
  p_grace_hours INT DEFAULT 24
)
RETURNS TABLE(
  path TEXT,
  size BIGINT,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  RETURN QUERY
  SELECT
    o.name::TEXT,
    o.metadata->>'size'::BIGINT,
    o.created_at
  FROM storage.objects o
  WHERE o.bucket_id = 'quote-models'
    AND o.created_at < NOW() - (p_grace_hours || ' hours')::INTERVAL
    AND NOT EXISTS (
      SELECT 1 FROM public.orders ord
      WHERE ord.file_url = o.name
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.quotes q
      WHERE q.file_path = o.name
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.model_files mf
      WHERE mf.file_url = o.name
    );
END;
$$;

REVOKE ALL ON FUNCTION public.cleanup_orphan_models(INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cleanup_orphan_models(INT) TO service_role;

-- Create admin_audit_logs table if it doesn't exist (used by cron jobs)
CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action      TEXT NOT NULL,
  target_type TEXT,
  target_id   TEXT,
  old_value   JSONB DEFAULT '{}'::jsonb,
  new_value   JSONB DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.admin_audit_logs ENABLE ROW LEVEL SECURITY;

-- Only service_role can access audit logs
CREATE POLICY "service_role_access" ON public.admin_audit_logs
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);
