import {
  LayoutDashboard,
  MessageCircle,
  ShoppingCart,
  ShoppingBag,
  Smartphone,
  Users,
  Package,
  BarChart3,
  CreditCard,
  Ticket,
  Settings,
  Building2,
  FileText,
  ShieldCheck,
  Beaker,
  Eye,
  Tag,
  ClipboardCheck,
  Star,
  Bell,
  Printer,
  ReceiptText,
  ScanSearch,
  Webhook,
  Factory,
  Database,
  Brain,
  Layers,
  Mail,
  Link,
  UserCog,
  FolderOpen,
  Warehouse,
  Megaphone,
} from 'lucide-react'

export type NavItem = {
  label: string
  href: string
  icon: React.ComponentType<{ className?: string }>
  section: 'main' | 'shop' | 'secondary'
  badge?: number
}

export const adminNavItems: NavItem[] = [
  { label: 'Dashboard', href: '/admin', icon: LayoutDashboard, section: 'main' },
  { label: 'Orders', href: '/admin/orders', icon: ShoppingCart, section: 'main' },
  { label: 'Customers', href: '/admin/customers', icon: Users, section: 'main' },
  { label: 'Quotes', href: '/admin/quotes', icon: ClipboardCheck, section: 'main' },
  { label: 'Payments', href: '/admin/payments', icon: CreditCard, section: 'main' },
  { label: 'Refunds', href: '/admin/refunds', icon: ReceiptText, section: 'main' },
  { label: 'Reconciliation', href: '/admin/reconciliation', icon: ScanSearch, section: 'main' },
  { label: 'Webhook Health', href: '/admin/webhook-health', icon: Webhook, section: 'main' },
  { label: 'Audit Logs', href: '/admin/audit-logs', icon: FileText, section: 'main' },
  { label: 'Email Center', href: '/admin/emails', icon: Mail, section: 'main' },
  { label: 'Printers', href: '/admin/printers', icon: Printer, section: 'main' },
  { label: 'Manufacturing', href: '/admin/manufacturing', icon: Factory, section: 'main' },
  { label: 'Materials', href: '/admin/materials', icon: Beaker, section: 'main' },
  { label: 'Promotions', href: '/admin/promotions', icon: Tag, section: 'main' },
  { label: 'Blog', href: '/admin/blog', icon: Eye, section: 'main' },
  { label: 'Analytics', href: '/admin/analytics', icon: BarChart3, section: 'main' },
  { label: 'Meta Ads', href: '/admin/ads', icon: Megaphone, section: 'main' },
  { label: '3D Shop Categories', href: '/admin/3d-shop/categories', icon: Layers, section: 'shop' },
  { label: '3D Shop Products', href: '/admin/3d-shop/products', icon: Package, section: 'shop' },
  { label: '3D Shop Stock', href: '/admin/3d-shop/stock', icon: Warehouse, section: 'shop' },
  { label: '3D Shop Orders', href: '/admin/3d-shop/orders', icon: ShoppingBag, section: 'shop' },
  { label: '3D Shop Reviews', href: '/admin/3d-shop/reviews', icon: Star, section: 'shop' },
  { label: '3D Shop Notify Me', href: '/admin/3d-shop/notify-me', icon: Bell, section: 'shop' },
  { label: 'Support Tickets', href: '/admin/tickets', icon: Ticket, section: 'secondary' },
  { label: 'Team & Roles', href: '/admin/team', icon: ShieldCheck, section: 'secondary' },
  { label: 'Users', href: '/admin/users', icon: UserCog, section: 'secondary' },
  { label: 'Files', href: '/admin/files', icon: FolderOpen, section: 'secondary' },
  { label: 'Data Retention', href: '/admin/settings/retention', icon: Database, section: 'secondary' },
  { label: 'Settings', href: '/admin/settings', icon: Settings, section: 'secondary' },
  { label: 'Business Settings', href: '/admin/settings/business', icon: Building2, section: 'secondary' },
  { label: 'WhatsApp Knowledge', href: '/admin/settings/whatsapp-knowledge', icon: Brain, section: 'secondary' },
  { label: 'WhatsApp Inbox', href: '/admin/whatsapp/inbox', icon: MessageCircle, section: 'secondary' },
  { label: 'WhatsApp Orders', href: '/admin/whatsapp/orders', icon: Smartphone, section: 'secondary' },
  { label: 'Account Linking', href: '/admin/account-linking', icon: Link, section: 'secondary' },
]
